version: 2
updates:
  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      material:
        patterns:
          - "@material-ui*"
      react:
        patterns:
          - "react*"

  # Maintain dependencies for backend
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group all updates together, so that they are all applied in a single PR.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      flux:
        patterns:
          - "*flux*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"

  # maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    labels: ["area/ci", "dependencies"]
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      # By default, this will be on a monday.
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
