version: 2
updates:
  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for backend
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"

  # maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    labels: ["area/ci", "dependencies"]
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      # By default, this will be on a monday.
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
