name: Docs

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'website/**'
  push:
    branches:
      - 'main'
    paths:
      - 'website/**'
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  staging-release:
    permissions:
      statuses: write
    if: ${{ github.event_name != 'push' && github.repository_owner == 'weaveworks' && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
      - name: Build docs
        env:
          GA_KEY: "dummy"
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          NODE_OPTIONS: "--max-old-space-size=4096"
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          yarn install --frozen-lockfile
          yarn clear
          export DOC_BASE_URL="/$GITHUB_HEAD_REF/"
          export DOC_URL=https://staging.docs.gitops.weave.works
          export STAGING_BUILD=true
          yarn build
      - id: auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2.1.3
        with:
          credentials_json: ${{ secrets.PROD_DOCS_GITOPS_UPLOAD }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # v2.1.0
        with:
          path: website/build
          destination: staging.docs.gitops.weave.works/${{ github.head_ref }}
          parent: false
          headers: |-
            cache-control: no-cache
      - id: add-docs-status
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          # Pull this out to a heredoc so we can easily interpolate variables
          PAYLOAD=$(cat <<EOF
          {
            "state": "success",
            "context": "Doc site preview",
            "target_url": "https://staging.docs.gitops.weave.works/$GITHUB_HEAD_REF"
          }
          EOF
          )

          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data "$PAYLOAD" \
            --fail

  prod-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
      - name: Build docs
        env:
          GA_KEY: ${{ secrets.GA_KEY }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          yarn install --frozen-lockfile
          yarn clear
          yarn build
      - id: auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2.1.3
        with:
          credentials_json: ${{ secrets.PROD_DOCS_GITOPS_UPLOAD }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # v2.1.0
        with:
          path: website/build
          destination: production.docs.gitops.weave.works
          parent: false
