on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'website/**'
      - '.github/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'website/**'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code
  packages: write

name: ♻️ PR CI Workflow
jobs:
  ci-js:
    name: 🧩 CI Test JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: 🗄️ Node modules cache
        uses: actions/cache@v4.0.2
        id: yarn-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: 🌐 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - run: corepack use yarn@stable && make node_modules
      - name: 📦 Check that package.json & package-lock.json were updated in commit
        run: |
          echo "Using node.js "$(node --version)
          echo "Using Yarn "$(yarn --version)
          git diff --no-ext-diff --exit-code
      - run: make ui-audit
      - run: make ui
      - run: make ui-lint
      - run: make ui-prettify-check
      - run: make ui-test
      - run: make ui-lib

  ci-go:
    name: 🧩 CI Test Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@ec141c63c49d31f58bdf3d606909a7fda8ebeb51 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: go mod tidy && git diff --no-ext-diff
      - run: make unit-tests
      # - run: make lib-test

  ci-static:
    name: 🧩 CI Check Static Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]
        node-version: [20]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: 🦍 Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - run: make check-format
      - run: make lint
      - run: go mod tidy
      - name: ☑️ Check that go mod tidy has been run
        run: git diff --no-ext-diff --exit-code
      - run: make proto
      - name: ☑️ Check that make proto has been run
        run: git diff --no-ext-diff --exit-code
      - run: make fakes
      - name: ☑️ Check that make fakes has been run
        run: git diff --no-ext-diff --exit-code

  ci-generate-tag:
    name: 🎰 CI Generate Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      - id: generate-tag
        run: echo "tag=$(date -u +%s)-${{ github.sha }}" >> $GITHUB_OUTPUT

  ci-build-gitops-image:
    name: 🏗️ CI Build Gitops Docker Image
    runs-on: ubuntu-latest
    needs: [ci-generate-tag]
    strategy:
      matrix:
        docker-image:
          - gitops
          - gitops-server
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: 🏴‍☠️ Set build-time flags
        run: |
          echo "LDFLAGS=$(make echo-ldflags)" >> $GITHUB_ENV
          echo "FLUX_VERSION=$(make echo-flux-version)" >> $GITHUB_ENV
      - name: 🚛 Build and export
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6.1.0
        with:
          tags: "ghcr.io/${{ github.repository }}/${{ matrix.docker-image }}:${{ needs.ci-generate-tag.outputs.tag }}"
          outputs: type=docker,dest=/tmp/${{ matrix.docker-image }}.tar
          file: ${{ matrix.docker-image }}.dockerfile
          build-args: |
            FLUX_VERSION=${{ env.FLUX_VERSION }}
            LDFLAGS=${{ env.LDFLAGS }}
            GIT_COMMIT=${{ github.sha }}
      - name: Load docker image
        run: docker load --input /tmp/${{ matrix.docker-image }}.tar
      - name: Cache docker image
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ matrix.docker-image }}
          path: /tmp/${{ matrix.docker-image }}.tar

  ci-upload-images:
    name: ⬆️ CI Upload Images
    runs-on: ubuntu-latest
    # Make sure we only upload images if tests etc have passed
    needs: [ci-go, ci-static, ci-js, ci-build-gitops-image, ci-generate-tag]
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event_name == 'push'
    strategy:
      matrix:
        docker-image:
          - gitops
          - gitops-server
    steps:
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Download cached docker image
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ matrix.docker-image }}
          path: /tmp
      
  ci-upload-binary:
    name: ⬆️ Upload Binary
    runs-on: ${{matrix.os}}
    needs: [ci-go, ci-static, ci-js, ci-build-gitops-image]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    if: github.event_name == 'push'
    steps:
    - name: Install Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: 1.22
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    - name: Clean
      run: make clean
    - id: gitsha
      run: |
        gitsha=$(git rev-parse --short ${{ github.sha }})
        echo "sha=$gitsha" >> $GITHUB_OUTPUT
    - name: build
      run: |
        make gitops

  ci-publish-js-lib:
    name: 🎁 Publish js library
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    needs: [ci-js]
    permissions:
      packages: write
    outputs:
      js-version: ${{ steps.package-version.outputs.js-version }}
    steps:
      - name: ⏳ Checkout
        uses: actions/checkout@v4.1.7
        with:
          # avoid the merge commit that on.pull_request creates
          # fallback to github.sha if not present (e.g. on.push(main))
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          # We want the correct sha so we can tag the npm package correctly
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"
      - run: yarn
      - run: make ui-lib
      - name: ⛳️ Update package version
        id: package-version
        uses: proudust/gh-describe@v2
      - run: |
          echo "describe  : ${{ steps.package-version.outputs.describe }}"
          echo "tag       : ${{ steps.package-version.outputs.tag }}"
          echo "distance  : ${{ steps.package-version.outputs.distance }}"
          echo "short-sha : ${{ steps.package-version.outputs.short-sha }}"
          GITOPS_VERSION=v0.39.0-${{ github.event.pull_request.head.sha || github.sha }}
          echo "js-version=$GITOPS_VERSION" >> $GITHUB_OUTPUT
          jq '.version = "'$GITOPS_VERSION'" | .name = "@${{ github.repository_owner }}/weave-gitops-main"' < dist/package.json > dist/package-new.json
          mv dist/package-new.json dist/package.json
          cp .npmrc dist
      - run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # We only push images on merge so create a passing check if everything finished
  finish-ci-pr:
    name: 🚀 PR CI Pipeline
    runs-on: ubuntu-latest
    needs:
      - ci-go
      - ci-static
      - ci-js
      - ci-build-gitops-image
    if: github.event_name != 'push'
    steps:
      - run: echo "All done"

  finish-ci-merge:
    # must match https://github.com/weaveworks/corp/blob/master/github-repo-weave-gitops.tf
    name: 🏁 Push CI Pipeline
    runs-on: ubuntu-latest
    needs:
      - ci-upload-images
      - ci-upload-binary
      - ci-publish-js-lib
    steps:
      - run: echo "All done"

  #  release step updates 'release' status check for non releases branches. See ../../doc/incidents/issues-3907 for full context.
  release:
    if: ${{ github.event_name == 'pull_request' && !startsWith(github.event.pull_request.head.ref, 'releases/') && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: ⚡️ Release
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
                "state":"success",
                "description":"release not required",
                "context":"release"
              }'
