name: Trigger Enterprise Workflow on Release or Merge

on:
  release:
    types:
      - created
  push:
    branches:
      - main

permissions:
  contents: none

jobs:
  trigger-enterprise-workflow:
    runs-on: ubuntu-latest
   # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.WKS_CI_TEST_BOT_PR_TOKEN }}
          repository: weaveworks/weave-gitops-enterprise
          event-type: create-pr
