name: Yarn Lock Changes
on: [pull_request, workflow_dispatch]

jobs:
  yarn_lock_changes:
    runs-on: ubuntu-latest
    # Permission overwrite is required for Dependabot PRs, see "Common issues" section below.
    permissions:
      pull-requests: write
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}
          
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit back
      # Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
